project_name: mqtt-log-stdout
builds:
- main: ./cmd/mqtt-log-stdout/main.go
  binary: mqtt-log-stdout
  ldflags:
  - -w -s -X main.Version={{ .Env.VERSION }} -X main.Revision={{ .Env.REVISION }} -X main.Created={{ .Env.CREATED }}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: binary
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc