version: "3.8"

services:
  vernemq:
    image: vernemq/vernemq
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    expose:
      - 1883
  client:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    links:
      - "vernemq"
    restart: always
