apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-log-stdout.fullname" . }}
  labels:
    {{- include "mqtt-log-stdout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mqtt-log-stdout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "mqtt-log-stdout.selectorLabels" . | nindent 8 }}
      {{- with .Values.extraPodLabels }}
        {{ toYaml . | indent 8 | trim }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: MQTT_HOST_1
              value: "{{ required "A valid .Values.mqtt_settings.host_1 entry required!" .Values.mqtt_settings.host_1 }}"
            {{- if .Values.mqtt_settings.host_2 }}
            - name: MQTT_HOST_2
              value: "{{ .Values.mqtt_settings.host_2 }}"
            {{- end }}
            {{- if .Values.mqtt_settings.host_3 }}
            - name: MQTT_HOST_3
              value: "{{ .Values.mqtt_settings.host_3 }}"
            {{- end }}
            - name: MQTT_PORT
              value: "{{ .Values.mqtt_settings.port }}"
            - name: LOG_TOPIC
              value: "{{ required "A valid .Values.mqtt_settings.topic entry required!" .Values.mqtt_settings.topic}}"
            - name: METRICS_PORT
              value: "{{ .Values.metrics.port }}"
            {{- if .Values.mqtt_settings.username }}
            - name: MQTT_USERNAME
              value: "{{ .Values.mqtt_settings.username }}"
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
