name: Coverage main

on:
  push:
    branches:
      - main

jobs:
  coverage-main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.19"
      - name: coverage
        run: |
          mkdir -p tmp
          make cover
      - name: Send coverage to coverall
        uses: shogo82148/actions-goveralls@v1.6.0
        with:
          path-to-profile: tmp/coverage.out
          ignore: cmd/mqtt-log-stdout/main.go,pkg/gen-docs/main.go